## Dream-Kit (Main-Config) ##
# Debug pokazuje dodatkowe informacje do konsoli. Lepiej wylaczyc. :P
debug: true
# Ustaw funkcje pluginu:
commands-config:
  # Mozesz zmienic ustawienia domyslne komend.
  kit-command:
    name: kit
    aliases:
    - kits
    - zestaw
    - zestawy
    description: Komenda do zestawow dla graczy.
    enabled: true
  kit-manage-command:
    name: kitmanage
    aliases: []
    description: Komenda do modyfikowania dostepnosci kitow.
    enabled: true
kit-config:
  # Ile wierszy ma posiadac gui?
  rows: 3
  # Ile wierszy ma posiadac gui z zestawem przedmiotow?
  rows-kit: 3
  # Jak gui ma sie nazywac?
  name: '&8&lZestawy'
  # Jak gui z zestawem przedmiotow ma sie nazywac?
  name-kit: '&2&lOdbierz zestaw!'
  # Jak gui z podgladem przedmiotow ma sie nazywac?
  name-kit-view: '&c&lPodglad zestawu'
  # Ustaw ulozenie itemow w twoim gui.
  # Ustawione itemy sa zablokowane event'em.
  items:
    0:
      material: LEATHER_BOOTS
      item-meta:
        display-name: '&8&lX-X'
        lore:
        - ' &7&lKit &8&lGRACZ:'
        - ' &4Delay: &7%TIME%'
        - ' '
        - '&7Kliknij &alewym&7, aby &6odebrac zestaw&7.'
        - '&7Kliknij &aprawym&7, aby obejrzec go.'
    1:
      material: IRON_BOOTS
      item-meta:
        display-name: '&8&lX-X'
        lore:
        - ' &7&lKit &e&lVIP:'
        - ' &4Delay: &7%TIME%'
        - ' '
        - '&7Kliknij &alewym&7, aby &6odebrac zestaw&7.'
        - '&7Kliknij &aprawym&7, aby obejrzec go.'
    2:
      material: GOLDEN_BOOTS
      item-meta:
        display-name: '&8&lX-X'
        lore:
        - ' &7&lKit &6&lSVIP:'
        - ' &4Delay: &7%TIME%'
        - ' '
        - '&7Kliknij &alewym&7, aby &6odebrac zestaw&7.'
        - '&7Kliknij &aprawym&7, aby obejrzec go.'
  # Uzupelnij liste kitow tak, jak ci sie podoba.
  # Domyslna permisja: dc.kit.[name]
  kit-list:
  - name: gracz
    cooldown-time: 600
    item-list:
    - material: DIAMOND_PICKAXE
      item-meta:
        enchantments:
          DIG_SPEED: 5
          LOOT_BONUS_BLOCKS: 3
          DURABILITY: 3
  - name: vip
    cooldown-time: 600
    item-list:
    - material: DIAMOND_HELMET
      item-meta:
        enchantments:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 3
    - material: DIAMOND_CHESTPLATE
      item-meta:
        enchantments:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 3
    - material: DIAMOND_LEGGINGS
      item-meta:
        enchantments:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 3
    - material: DIAMOND_BOOTS
      item-meta:
        enchantments:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 3
    - material: DIAMOND_SWORD
      item-meta:
        enchantments:
          FIRE_ASPECT: 2
          DAMAGE_ALL: 6
    - material: DIAMOND_SWORD
      item-meta:
        enchantments:
          KNOCKBACK: 2
          DAMAGE_ALL: 6
    - material: DIAMOND_PICKAXE
      item-meta:
        enchantments:
          DIG_SPEED: 5
          LOOT_BONUS_BLOCKS: 3
          DURABILITY: 3
    - material: GOLDEN_APPLE
      amount: 32
      durability: 1
      item-meta: {}
    - material: GOLDEN_APPLE
      amount: 64
    - material: ENDER_PEARL
      amount: 64
  - name: svip
    cooldown-time: 600
    item-list:
    - material: DIAMOND_HELMET
      item-meta:
        enchantments:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 3
    - material: DIAMOND_CHESTPLATE
      item-meta:
        enchantments:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 3
    - material: DIAMOND_LEGGINGS
      item-meta:
        enchantments:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 3
    - material: DIAMOND_BOOTS
      item-meta:
        enchantments:
          PROTECTION_ENVIRONMENTAL: 6
          DURABILITY: 3
    - material: DIAMOND_SWORD
      item-meta:
        enchantments:
          FIRE_ASPECT: 2
          DAMAGE_ALL: 6
    - material: DIAMOND_SWORD
      item-meta:
        enchantments:
          KNOCKBACK: 2
          DAMAGE_ALL: 6
    - material: DIAMOND_PICKAXE
      item-meta:
        enchantments:
          DIG_SPEED: 5
          LOOT_BONUS_BLOCKS: 3
          DURABILITY: 3
    - material: GOLDEN_APPLE
      amount: 32
      durability: 1
      item-meta: {}
    - material: GOLDEN_APPLE
      amount: 64
    - material: ENDER_PEARL
      amount: 64
  # Jaki slot odpowiada danemu kitowi?
  item-event:
    0: gracz
    1: vip
    2: svip
  back-button:
    material: REDSTONE
    item-meta:
      display-name: '&4Powrot do zestawow.'
