## Dream-Uprawnienia (config.yml) ##
# Dostepne type: (CHAT, ACTION_BAR, SUBTITLE, TITLE, TITLE_SUBTITLE)
status-on: '&aNadane'
status-off: '&cNie nadane'

build: true
break-block: true
open-chest: true
spilling-water-and-lava: true
place-tnt: true
teleport-players: true
break-beacon: true

build-message:
  type: CHAT
  message: '&cNie masz uprawnien do stawiania blokow na terenie gildii'
place-tnt-message:
  type: CHAT
  message: '&cNie masz uprawnien do stawiania tnt na terenie gildii'
break-message:
  type: CHAT
  message: '&cNie masz uprawnien do niszczenia na terenie gildii'
break-beacon-message:
  type: CHAT
  message: '&cNie masz uprawnien do niszczenia beacon na terenie gildii'
open-chest-message:
  type: CHAT
  message: '&cNie masz uprawnien do otwierania skrzynek'
spilling-message:
  type: CHAT
  message: '&cNie masz uprawnien wylewania wody i lawy na terenie gildii'
teleport-message:
  type: CHAT
  message: '&cNie masz teleportowac innych osob na teren gildii'
teleport-commands:
- tpaccept
- tphere

message-correct-use:
  type: CHAT
  message: '&7Poprawne uzycie: &c/uprawnienia <nick>'
message-no-guild:
  type: CHAT
  message: '&cNie posiadasz gildii'
message-no-owner:
  type: CHAT
  message: '&cNie jestes liderem gildii'
message-player-has-owner:
  type: CHAT
  message: '&cNie mozesz zmienac uprawnien samemu sobie'
message-player-no-guild:
  type: CHAT
  message: '&cTen gracz nie posiada gildii'
message-not-your-guild:
  type: CHAT
  message: '&cTen gracz nie jest w twojej gildii'
message-player-offline:
  type: CHAT
  message: '&cTen gracz jest offline'
