## Dream-Schowek (config.yml) ##
# Dostepne type: (CHAT, ACTION_BAR, SUBTITLE, TITLE, TITLE_SUBTITLE)
gui-name: '&4&lSCHOWEK'
gui-size: 3
task-time: 3

items:
- item:
    material: ENCHANTED_GOLDEN_APPLE
    durability: 1
    item-meta: {}
  limit: 2
- item:
    material: GOLDEN_APPLE
  limit: 16
- item:
    material: ENDER_PEARL
  limit: 4
- item:
    material: EMERALD_BLOCK
  limit: 256
- item:
    material: TOTEM_OF_UNDYING
  limit: 3

task-message:
  type: CHAT
  message: '&cTwoje przedmioty zostaly przeniesione do schowka'
ppm-error-message:
  type: CHAT
  message: '&cNie masz 64 przedmiotow w schowku'
ppm-success-messagee:
  type: CHAT
  message: '&aWyplaciles 64 przedmioty ze schowka'
lpm-error-message:
  type: CHAT
  message: '&cNie masz 1 przedmiotow w schowku'
lpm-success-messagee:
  type: CHAT
  message: '&aWyplaciles 1 przedmioty ze schowka'
all-success-message:
  type: CHAT
  message: '&aWyplaciles caly limit'
