# zmienna do nicku {NICK} i mozesz uzywac & a nie paragrafy pozdro by FCODE



pomoc:
- '&c&LPomoc serwerowa:'
- ''
- '&f/drop &8- &7Drop serwerowy'
- '&f/gildia &8- &7Przydatne komendy gildijne'
- '&f/schowek &8- &7Przenośny depozyt na itemki'
- '&f/kit &8- &7Zestawy serwerowe'
- '&f/sklep &8- &7Sklep serwerowy'
- ''
- '&f/vip &8- &7Informacje o randze vip'
- '&f/svip &8- &7Informacje o randze svip'
- '&f/mvp &8- &7Informacje o randze mvp'
vip:
- ' '
- ' &8» &7Lista udogodnień rangi &6&lVIP&8:'
- '  &8• &f/kit vip &8- &7Zestaw rangi VIP'
- '  &8• &f/workbench &8- &7Przenosny crafting'
- '  &8• &f/repair &8- &7Mozliwość naprawy przedmiotu'
- ' '
- ' &8» &7Lista dodatkowych udogodnien rangi &6&LVIP&8:'
- '  &8• &fMożliwość stworzenia 2 domów'
- '  &8• &fZwiększony drop z kamienia o 3%'
- ' '
- ' &8» &7Formalności dla rangi &6&LVIP&8:'
- '  &8• &7Cena: &f5 PLN'
- ' '
svip:
- ' '
- ' &8» &7Lista udogodnień rangi &e&lSVIP&8:'
- '  &8• &f/kit vip &8- &7Zestaw rangi VIP'
- '  &8• &f/kit svip &8- &7Zestaw rangi SVIP'
- '  &8• &f/workbench &8- &7Przenosny crafting'
- '  &8• &f/repair &8- &7Mozliwość naprawy przedmiotu'
- '  &8• &f/repair all &8- &7Mozliwość naprawy przedmiotów'
- ' '
- ' &8» &7Lista dodatkowych udogodnien rangi &e&LSVIP&8:'
- '  &8• &fMożliwość stworzenia 3 domów'
- '  &8• &fZwiększony drop z kamienia o 4%'
- ' '
- ' &8» &7Formalności dla rangi &e&LSVIP&8:'
- '  &8• &7Cena: &f5 PLN'
- ' '
mvp:
- ' '
- ' &8» &7Lista udogodnień rangi &2&LMVP&8:'
- '  &8• &f/kit vip &8- &7Zestaw rangi VIP'
- '  &8• &f/kit svip &8- &7Zestaw rangi SVIP'
- '  &8• &f/kit mvp &8- &7Zestaw rangi MVP'
- '  &8• &f/workbench &8- &7Przenosny crafting'
- '  &8• &f/repair &8- &7Mozliwość naprawy przedmiotu'
- '  &8• &f/repair all &8- &7Mozliwość naprawy przedmiotów'
- '  &8• &f/freeturbo &8- &7Darmowy turbo drop'
- ' '
- ' &8» &7Lista dodatkowych udogodnien rangi &2&LMVP&8:'
- '  &8• &fMożliwość stworzenia 4 domów'
- '  &8• &fZwiększony drop z kamienia o 5%'
- ' '
- ' &8» &7Formalności dla rangi &2&LMVP&8:'
- '  &8• &7Cena: &f10 PLN'
- ' '
yt:
- ' '
- ' &7Ranga &fYou&4Tuber &7posiada to samo co &6VIP'
- ' &7Ranga &fYou&4Tuber&6+ &7posiada to samo co &eSVIP'
- '   &8+ &7własny kit, &e/kit yt'
- '  &7Range &fYou&4Tuber &7otrzymasz za &f300-999 &7subów!'
- '  &7A range &fYou&4Tuber&6+ &7otrzymasz za &f1000+ &7subów!'
- '  &7Aby otrzymać range wrzuć trailer na swój kanał i zgłoś się na dc.XyzMC.pl'
- ' &9&lNAGRANIE MUSISZ NAGRAĆ SAM! &7Dlatego że my nagrywamy trailer do publikacji
  XD'
- ''
dc:
- ''
- '&7Link do discorda: &fdc.XyzMC.pl'
- ''
fb:
- ''
- '&7Link do fanpage: &ffb.XyzMC.pl'
- ''
