## Drop (config.yml) ##

# Opcje
pickaxe-in-hand: true
creative-break: false
ore-drop: false
drop-premium-perms: drop.premium
# Dostepne opcje:
# CHAT
# ACTIONBAR
# TITLE
# SUBTITLE
drop-message-type: CHAT

# ALL
status-on: '&awlaczony'
status-off: '&cwylaczony'

# Hopper
hopper-name: '&cWypadanie podczas pelnego ekwipunku'
hopper-description:
- ''
- '&cStatus: {STATUS}'
- ''
hopper-status-on: '&awlaczony'
hopper-status-off: '&cwylaczony'

# Cobble
cobble-name: '&cDrop cobbla'
cobble-description:
- ''
- '&cStatus: {STATUS}'
- ''
cobble-status-on: '&awlaczony'
cobble-status-off: '&cwylaczony'

# On-ALL
on-name: '&aWlacz wszystkie dropy'
on-description:
- ''

# Off-ALL
off-name: '&cWylacz wszystkie dropy'
off-description:
- ''

# Message
message-name: '&cZmien status wiadomosci'
message-description:
- ''
- '&cStatus: {STATUS}'
- ''

# LuckyBlock-Status
luckyblock-status-name: '&cKliknij aby zobaczyc drop z ultrabloku'
luckyblock-status-description:
- ''
- '&cStatus: {STATUS}'
- ''

# TNT
tnt-name: '&cKliknij aby zmienic status tnt'
tnt-description:
- ''
- '&cStatus: {STATUS}'
- ''

# LuckyBlock
luckyblock-name: '&cWejdz do gui luckyblocka'
luckyblock-description:
- '&cKliknij PPM, aby przelaczyc gui'

# Cobblex
cobblex-name: '&cKliknij aby zobaczyc drop z cobblex'
cobblex-description:
- ''

# Tnt-UltraBlock
tnt-message: '&aGratulacje wydropiles rzucanetnt'
tnt-command: rzucane daj {PLAYER} 1

# PermiumCase
premiumcase-name: '&cKliknij aby zobaczy drop z PremiumCase'
premiumcase-description:
- ''
- ''
- ''

# Pandora
pandora-name: '&cKliknij aby zobaczy drop z Pandory'
pandora-description:
- ''
- ''
- ''

# Komenda turbo
turbo-correct-use: '&cPoprawne uzycie: &9/turbo <drop/sdrop/exp> <all/nick/guild>
  [tag] <czas np. 1h>'
turbo-no-intiger: '&cTo nie jest liczba'
turbo-success: '&aGratulacje wlaczyles event {EVENT} na {TIME}'
turbo-no-perms: '&cNie posiadasz permissji do tej komendy'
turbo-perms: drop.turbo
turbo-player-offline: '&cTen gracz jest offline'
turbo-success-player: '&aGratulacje wlaczyles event {EVENT} na {TIME} dla gracza {PLAYER}'
turbo-success-guild: '&aGratulacje wlaczyles event {EVENT} na {TIME} dla gildii {GUILD}'
turbo-correct-use-player: '&cPoprawne uzycie: &9/event <turbodrop/dropcase> <all/nick>
  <czas np. 1h>'
turbo-actionbar-info: true
turbodrop-actionbar-message: '&3&lTURBO-DROP &8(&c{TIME}&8) '
turboexp-actionbar-message: ' &6&lTURBO-EXP &8(&c{TIME}&8)'
sturbodrop-actionbar-message: ' &d&lSUPER-TURBO-DROP &8(&c{TIME}&8)'
lvl-message-on: '&aWiadomosc o lvlup zostala wlaczona'
lvl-message-off: '&cWiadomosc o lvlup zostala wylaczona'
events-perms: drop.events
events-perms-message: '&cNie masz uprawnien do tej komendy'
case-perms: drop.events
case-perms-message: '&cNie masz uprawnien do tej komendy'
case-null: '&cNie ma takiej skrzynki'
case-player-offline: '&cTen gracz jest offline'
case-no-intiger: '&cTo nie jest liczba'
case-correct-use: '&cPoprawne uzycie: /case <case> <nick/all> <ilosc>'
case-success: '&aGratulacje dales graczowi {PLAYER} {CASE} w ilosci {AMOUNT}'
voucher-perms: drop.events
voucher-perms-message: '&cNie masz uprawnien do tej komendy'
voucher-null: '&cNie ma takiego vouchera'
voucher-player-offline: '&cTen gracz jest offline'
voucher-no-intiger: '&cTo nie jest liczba'
voucher-correct-use: '&cPoprawne uzycie: /givevoucher <voucher> <nick/all> <ilosc>'
voucher-success: '&aGratulacje dales graczowi {PLAYER} {VOUCHER} w ilosci {AMOUNT}'
case-on-message: '&aInformacje o dropie premiumcase zostaly wlaczone'
case-on-message-error: '&aWiadomosci sa juz wlaczone'
case-off-message: '&aInformacje o dropie premiumcase zostaly wylaczone'
case-off-message-error: '&aWiadomosci sa juz wylaczone'
free-turbo-perms: drop.freeturbo
free-turbo-perms-message: '&cNie posiadasz permissji do tej komendy'
free-turbo-success-message: '&cGratulacje uzyles komendy'
free-turbo-time-error: '&cPoczekaj prze nastepnym uzyciem komendy ({TIME})'
free-turbo-time-use: 10
free-turbo-time: 2h
ksiazka-success: '&aGratulacje uzyles vouchera'
ksiazka-error: '&cTo nie jest voucher'
ksiazka-is-off: '&cObecnie vouchery sa wylaczone'
premium-items-format: '- {NAME} x{AMOUNT}'
premium-null: '- Brak'
premium-action-bar-message: '&cotworzyles case'
premium-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

iron-items-format: '- {NAME} x{AMOUNT}'
iron-null: '- Brak'
iron-action-bar-message: '&cotworzyles case'
iron-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

gold-items-format: '- {NAME} x{AMOUNT}'
gold-null: '- Brak'
gold-action-bar-message: '&cotworzyles case'
gold-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

diamond-items-format: '- {NAME} x{AMOUNT}'
diamond-null: '- Brak'
diamond-action-bar-message: '&cotworzyles case'
diamond-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

emerald-items-format: '- {NAME} x{AMOUNT}'
emerald-null: '- Brak'
emerald-action-bar-message: '&cotworzyles case'
emerald-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

stone-items-format: '- {NAME} x{AMOUNT}'
stone-null: '- Brak'
stone-action-bar-message: '&cotworzyles case'
stone-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

ultrablock-items-format: '- {NAME} x{AMOUNT}'
ultrablock-null: '- Brak'
ultrablock-action-bar-message: '&cotworzyles case'
ultrablock-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

cobblex-items-format: '- {NAME} x{AMOUNT}'
cobblex-null: '- Brak'
cobblex-action-bar-message: '&cotworzyles case'
cobblex-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

pandora-items-format: '- {NAME} x{AMOUNT}'
pandora-null: '- Brak'
pandora-action-bar-message: '&cotworzyles case'
pandora-message-all:
- '&cGracz {PLAYER} otworzyl {NAME}'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'

widmo-name: '&cWidmo'
widmo-health: 1000.0
widmo-items-format: '- {NAME} x{AMOUNT}'
widmo-null: '- Brak'
widmo-action-bar-message: '&cZabiles Widmo'
widmo-message-all:
- '&cGracz {PLAYER} zabil WIDMO'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'
widmo-hp-message: '&cWidmo ma obecnie {HP}/{MAX}'
widmo-hp-event-off: '&cObecnie event widmo jest wylaczony'
widmo-difficulty-error: '&cNie mozesz przyzwac widmo na tym poziomie trudnosci'
widmo-event-info: '&cGlowe widmo musisz postawic nad blokiem zlota'

giant-name: '&cBOSS'
giant-health: 1000.0
giant-items-format: '- {NAME} x{AMOUNT}'
giant-null: '- Brak'
giant-action-bar-message: '&cZabiles BOSSA'
giant-message-all:
- '&cGracz {PLAYER} zabil BOSSA'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'
giant-hp-message: '&cBOSS ma obecnie {HP}/{MAX}'
giant-hp-event-off: '&cObecnie event gigant jest wylaczony'
giant-difficulty-error: '&cNie mozesz przyzwac widmo na tym poziomie trudnosci'

snowman-name: '&cSNOWMAN'
snowman-health: 100.0
snowman-items-format: '- {NAME} x{AMOUNT}'
snowman-null: '- Brak'
snowman-action-bar-message: '&cZabiles Balwana'
snowman-message-all:
- '&cGracz {PLAYER} zabil Balwana'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'
snowman-hp-message: '&cBawlan ma obecnie {HP}/{MAX}'
snowman-hp-event-off: '&cObecnie event gigant jest wylaczony'
snowman-difficulty-error: '&cNie mozesz przyzwac balwana na tym poziomie trudnosci'

zombie-name: '&cZOMBIE'
zombie-health: 100.0
zombie-items-format: '- {NAME} x{AMOUNT}'
zombie-null: '- Brak'
zombie-action-bar-message: '&cZabiles zombie'
zombie-message-all:
- '&cGracz {PLAYER} zabil Zombie'
- '&cWydropil'
- '{ITEMS}'
- '&c-----'
zombie-hp-message: '&cZombie ma obecnie {HP}/{MAX}'
zombie-hp-event-off: '&cObecnie event zombie jest wylaczony'
zombie-difficulty-error: '&cNie mozesz przyzwac zombie na tym poziomie trudnosci'

animation-gui-name: '&cPremiumCase'

lvl:
- 1;200
- 2;400
lvl-title-message: '&4&lLVL'
lvl-sub-title-message: '&aGratulacje osiagnoles {LVL} Lvl.'
lvl-message: '&aGratulacje osiagnoles {LVL} Lvl'
